### ISSUE TITLE
Como visitante eu quero ver a tela do evento

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#13]
1. O sistema consulta o evento (encontra usando parâmetro de rota)
2. O sistema apresenta o evento encontrado para o usuário ou direciona para a página de evento não encontrado

A tela deve apresentar os detalhes do evento, conforme descritos na página [Evento](https://github.com/fswceulp/sistema-eventos-front/wiki/Evento) da Wiki.

**Comment by IanMaiwald** [comment]
![tela - issue 13](https://cloud.githubusercontent.com/assets/25598652/26332630/49513bba-3f2e-11e7-9df2-a8a76ae6b90a.png)

A parte preta no topo é barra de navegação que vai ser ignorada nesse layout

**Comment by jacksongomesbr** [comment]
Os itens "Programação" e "Artigos" não deveriam ser apresentados diretamente nesta página. Entretanto, isso pode ser combinado com os desenvolvedores responsáveis, de modo que eles implementem suas funcionalidades na forma de componentes que serão inseridos aqui, tornando o "site do evento" no formato "uma página".

**Comment by IanMaiwald** [comment]
![tela - issue 13 e 14](https://cloud.githubusercontent.com/assets/25598652/26333970/292747a8-3f38-11e7-9ac4-e593d1b47f63.png)

O item "Programação" agora é apenas um botão que leva para a tela de programação daquele evento.
O item "Artigos" se refere ao issue #14, que também é minha parte. Eu optei por deixar os dois issues na mesma página.
