### ISSUE TITLE
Como visitante eu quero ver a tela de artigos publicados no evento

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#14]
A tela de artigos apresenta a lista de artigos publicados no evento.

**Comment by IanMaiwald** [comment]
![tela - issue 13 e 14 destacado](https://cloud.githubusercontent.com/assets/25598652/26334113/11a20004-3f39-11e7-9784-85c5a2db0b49.png)

Os issues #13 e #14 são minha parte e eu optei por deixá-los juntos.
A parte destacada (que não faz parte do layout) se refere ao issue #14
