### ISSUE TITLE
Como usuário eu quero ver a tela de login

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#17]
A tela de login deve permitir ao usuário entrar no sistema fornecendo suas credenciais (login e senha). Se as credenciais fornecidas estiverem corretas, o usuário deve ser direcionado para a área administrativa, caso contrário o sistema deve apresentar uma mensagem indicando o erro.

**Comment by AlexandreKavalerski** [comment]
![login-screen](https://cloud.githubusercontent.com/assets/25331207/26498853/d995762a-4206-11e7-9205-3edec9381a6a.png)

Mudei de ideia em relação ao que tinha falado antes (sobre a opção de login estar em um dropdown no menu superior do site o tempo inteiro). Agora o Login será em uma página separada. A imagem com o texto "LOGO" refere-se ao logo do site e não a uma eventual foto de perfil do usuário.

**Comment by AlexandreKavalerski** [comment]
![image](https://cloud.githubusercontent.com/assets/25331207/26564303/b852a6f2-44b5-11e7-9d5b-56e93b3a7766.png)
Nova Tela
