### ISSUE TITLE
Como visitante eu quero ver a tela de cadastro de usuário

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#18]
A tela de cadastro de usuário deve permitir ao visitante criar uma conta de acesso ao sistema. Para tal, deve fornecer os dados:

- e-mail (será usado como nome de usuário)
- senha

O usuário poderá fornecer outros dados posteriormente, na tela de edição do perfil.

**Comment by AlexandreKavalerski** [comment]
![cadastro-sistema-eventos](https://cloud.githubusercontent.com/assets/25331207/26785018/d41d74d6-49d6-11e7-9ad0-d373f79a9028.png)
