### ISSUE TITLE
Como usuário eu quero ver a tela do meu perfil

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#20]
O usuário deve poder acessar a tela do seu perfil. A partir dessa tela deve ser possível acessar a funcionalidade de edição do perfil. O usuário pode fornecer os dados:

- nome completo
- e-mail
- senha (alterar senha)
- endereço
- telefone

**Comment by AlexandreKavalerski** [comment]
![perfil-sistema-eventos](https://cloud.githubusercontent.com/assets/25331207/26789267/19297548-49e6-11e7-9ace-321f59941f0c.png)
