### ISSUE TITLE
Como administrador eu quero ver a lista de Estados

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#25]
Na área administrativa, o usuário com permissão de administrador deve poder ver a lista dos Estados cadastrados. Cada item da lista deve permitir executar as ações: editar e excluir. A tela também deve permitir ao usuário:

- Filtrar a lista de Estados (por nome, por UF)
- Ver a lista de Estados de forma paginada

**Comment by marcusmarcelino** [comment]
![listaestados](https://cloud.githubusercontent.com/assets/25598984/26333776/bb59e966-3f36-11e7-8fb8-2478f6efb567.png)

**Comment by marcusmarcelino** [comment]
![lista](https://user-images.githubusercontent.com/25598984/27331263-20ccca12-5593-11e7-819e-662ab050a687.png)
