### ISSUE TITLE
Como administrador eu quero cadastrar um Estado

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#26]
Na área administrativa, o usuário com permissão de administrador deve poder cadastrar um Estado.

**Comment by marcusmarcelino** [comment]
![cadastro edicao](https://cloud.githubusercontent.com/assets/25598984/26333782/d16484c8-3f36-11e7-93e6-6026e7ac2bb1.png)

**Comment by marcusmarcelino** [comment]
![cadastro](https://user-images.githubusercontent.com/25598984/27331304-41a7c9e4-5593-11e7-9424-73726d635b1e.png)
