### ISSUE TITLE
Como administrador eu quero editar um Estado

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#27]
Na área administrativa, o usuário com permissão de administrador deve poder editar os dados de um Estado.

**Comment by marcusmarcelino** [comment]
![cadastro edicao](https://cloud.githubusercontent.com/assets/25598984/26333864/6a3f6514-3f37-11e7-8438-80617c2cedcf.png)

**Comment by marcusmarcelino** [comment]
![editar](https://user-images.githubusercontent.com/25598984/27331342-61875d10-5593-11e7-97f5-7598470a6a37.png)
