### ISSUE TITLE
Como administrador eu quero excluir um Estado

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#28]
Na área administrativa, o usuário com permissão de administrador deve poder excluir um Estado. O sistema deve solicitar uma confirmação do usuário antes de, efetivamente, proceder com a exclusão.

**Comment by marcusmarcelino** [comment]
![excluir](https://cloud.githubusercontent.com/assets/25598984/26333856/6067ce0a-3f37-11e7-955e-f00176ad7da9.png)

**Comment by marcusmarcelino** [comment]
![excluir](https://user-images.githubusercontent.com/25598984/27331355-7468880a-5593-11e7-8a9b-e09e31b93518.png)
