### ISSUE TITLE
Como administrador eu quero ver a lista de Cidades

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#29]
Na área administrativa, o usuário com permissão de administrador deve poder ver a lista das Cidades cadastradas. Cada item da lista deve permitir executar as ações: editar e excluir. A tela também deve permitir ao usuário:

- Filtrar a lista de Cidades (por nome)
- Ver a lista de Cidades de forma paginada

**Comment by jhemesonmotta** [comment]
![lista de cidades](https://cloud.githubusercontent.com/assets/25598816/26331996/6fc5f30c-3f2a-11e7-8314-b93ebb542844.jpg)
