### ISSUE TITLE
Como administrador eu quero cadastrar uma Cidade

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#30]
Na área administrativa, o usuário com permissão de administrador deve poder cadastrar uma Cidade.

**Comment by jhemesonmotta** [comment]
![formulario](https://cloud.githubusercontent.com/assets/25598816/26332631/4959ed50-3f2e-11e7-884f-315a8864e7ac.jpg)

**Comment by jhemesonmotta** [comment]
![formulario 3](https://cloud.githubusercontent.com/assets/25598816/26333196/2d152b92-3f32-11e7-8411-b08a5e958d10.jpg)
