### ISSUE TITLE
Como administrador eu quero editar uma Cidade

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#31]
Na área administrativa, o usuário com permissão de administrador deve poder editar os dados de uma Cidade.

**Comment by jhemesonmotta** [comment]
![formulario 1](https://cloud.githubusercontent.com/assets/25598816/26332628/465028c2-3f2e-11e7-9405-5635f717fd7f.jpg)

**Comment by jacksongomesbr** [comment]
@jhemesonmotta Não deve solicitar do usuário que ele informe o "id" da cidade.

**Comment by jhemesonmotta** [comment]
![formulario 2](https://cloud.githubusercontent.com/assets/25598816/26333175/096d4a94-3f32-11e7-845b-5009364b046f.jpg)
