### ISSUE TITLE
Como administrador eu quero excluir uma Cidade

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#32]
Na área administrativa, o usuário com permissão de administrador deve poder excluir uma Cidade. O sistema deve solicitar uma confirmação do usuário antes de, efetivamente, proceder com a exclusão.

**Comment by jhemesonmotta** [comment]
![excluir](https://cloud.githubusercontent.com/assets/25598816/26333151/e00d554a-3f31-11e7-8d13-51991b47ae6b.jpg)
