### ISSUE TITLE
Como administrador eu quero cadastrar um Usuário

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#34]
Na área administrativa, o usuário com permissão de administrador deve poder cadastrar um Usuário. Considerando que Usuário e Pessoa representam a mesma entidade, os dados para cadastro são:

- Nome completo
- E-mail (usado também como nome de usuário)
- Senha
- Endereço
- Telefone

**Comment by AlexandreMT** [comment]
![cadastra-edita](https://cloud.githubusercontent.com/assets/25598649/26333255/a1f35c7c-3f32-11e7-9d54-96a4f680ca65.png)
