### ISSUE TITLE
Como administrador eu quero ver a lista de Usuários

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#35]
Na área administrativa, o usuário com permissão de administrador deve poder ver a lista dos Usuários cadastrados. Cada item da lista deve permitir executar as ações: editar e excluir. A tela também deve permitir ao usuário:

- Filtrar a lista de Usuários (por nome completo, e-mail, endereço)
- Ver a lista de Usuários de forma paginada

**Comment by AlexandreMT** [comment]
![lista usuarios](https://cloud.githubusercontent.com/assets/25598649/26333240/83382bb4-3f32-11e7-8fa4-f24668cbecc0.png)

**Comment by jacksongomesbr** [comment]
Retirar a parte da confirmação da exclusão
