### ISSUE TITLE
Como administrador eu quero editar um Usuário

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#36]
Na área administrativa, o usuário com permissão de administrador deve poder ver editar um Usuário.

**Comment by AlexandreMT** [comment]
![cadastra-edita](https://cloud.githubusercontent.com/assets/25598649/26333353/600310b8-3f33-11e7-8874-844b0a70f752.png)

**Comment by jacksongomesbr** [comment]
Ok, mas melhore nos ícones (se for adotar esse padrão mesmo).
