### ISSUE TITLE
Como administrador eu quero excluir um Usuário

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#37]
Na área administrativa, o usuário com permissão de administrador deve poder excluir um Usuário. O sistema deve solicitar uma confirmação do usuário antes de, efetivamente, proceder com a exclusão.

**Comment by AlexandreMT** [comment]
![lista usuarios](https://cloud.githubusercontent.com/assets/25598649/26333360/6cea7f14-3f33-11e7-8688-33a5c4bfa894.png)
