### ISSUE TITLE
Como administrador eu quero gerenciar os Usuários

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#38]
Ao acessar a área administrativa, o usuário com permissão de administrador deve poder executar funcionalidades:

- Ver a lista de Usuários (#35)
- Cadastrar Usuário (#34)
- Editar Usuário (#36)
- Excluir Usuário (#37)

No contexto desse sistema, Usuário está diretamente relacionado com Pessoa, não sendo obrigatório utilizar, por exemplo, duas entidades para representar esses dados.

**Comment by AlexandreMT** [comment]
![lista usuarios](https://cloud.githubusercontent.com/assets/25598649/26333369/79733460-3f33-11e7-823f-9411089e2a95.png)

**Comment by jacksongomesbr** [comment]
Aqui não deve ser a mesma tela da exclusão
