### ISSUE TITLE
Como administrador ou realizador de evento eu quero ver a lista de Eventos

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#39]
Na área administrativa, o usuário com permissão de administrador ou realizador de evento deve poder ver a lista dos Eventos cadastrados. O usuário administrador deve poder ver a lista de todos os eventos. O usuário realizador de evento deve poder ver a lista apenas dos eventos realizados (cadastrados) por ele.

Cada item da lista deve permitir executar as ações: editar e excluir. A tela também deve permitir ao usuário:

- Filtrar a lista de Eventos (por nome, sigla, ano, nome do realizador, local -- nome da cidade, nome do Estado ou UF do Estado)
- Ver a lista de Eventos de forma paginada

**Comment by laercionunesc** [comment]
![lista_de_eventos](https://cloud.githubusercontent.com/assets/13398775/26332891/245509a2-3f30-11e7-9a65-bc69fcdde522.png)

**Comment by jacksongomesbr** [comment]
@laercio159 Procure usar uma imagem exclusiva para cada issue.
