### ISSUE TITLE
Como usuário eu quero cadastrar um Evento

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#40]
Na área administrativa, o usuário deve poder cadastrar um Evento. Os dados para cadastro são

- nome
- sigla
- descrição
- data de início
- data de término
- palavras-chave

No momento do cadastro, o sistema deve considerar que o **realizador do evento** é o usuário que está utilizando o sistema no momento.

**Comment by laercionunesc** [comment]
![adicionar_evento](https://cloud.githubusercontent.com/assets/13398775/26333528/aba50a3e-3f34-11e7-919c-74580cf88916.png)
