### ISSUE TITLE
Como realizador de evento ou administrador eu quero gerenciar os Eventos

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#41]
Ao acessar a área administrativa, o usuário com permissão de realizador de evento ou administrador deve poder executar funcionalidades:

- Ver a lista de Eventos (#39)
- Cadastrar Evento (#40)
- Editar Evento (#42)
- Excluir Evento (#43)

**Comment by laercionunesc** [comment]
![adicionar_evento](https://cloud.githubusercontent.com/assets/13398775/26333502/881651a4-3f34-11e7-96ae-150cfc05a6b9.png)
![editar_evento](https://cloud.githubusercontent.com/assets/13398775/26333501/881638fe-3f34-11e7-9140-78a79c402bc0.png)
![lista_de_eventos](https://cloud.githubusercontent.com/assets/13398775/26332843/de8e80a6-3f2f-11e7-87c1-bd9e574b8ad6.png)

**Comment by jacksongomesbr** [comment]
@laercio159 Faltou indicar a localização do Evento (Cidade, Estado).
