### ISSUE TITLE
Como realizador do evento ou administrador eu quero gerenciar a Programação do Evento

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#45]
Na área administrativa, o usuário com permissão de realizador do evento ou administrador deve poder gerenciar a programação do Evento. Essa funcionalidade deve ser acessada a partir da tela da lista dos eventos (ver #39). 

Nessa tela o usuário deve poder:

- ver a lista de itens da programação
- cadastrar item da programação
- editar item da programação
- excluir item da programação

Para mais informações, ver a [página do Evento](https://github.com/fswceulp/sistema-eventos-front/wiki/Evento) na Wiki.

**Comment by lucasribeirorsousa** [comment]
**VER LISTA DE ITENS DA PROGRAMAÇÃO: **
![gerenciarprogramacao-lista](https://cloud.githubusercontent.com/assets/25598885/26369181/45c7b054-3fca-11e7-8700-261b0ad5aa6e.jpg)

**EXCLUIR ITEM DA PROGRAMAÇÃO: **
![gerenciarprogramacao-excluir 1](https://cloud.githubusercontent.com/assets/25598885/26369320/b6d2fa88-3fca-11e7-8775-14f767d01c57.jpg)

**CADASTRAR ITEM DA PROGRAMAÇÃO: **
![gerenciarprogramacao-cadastro](https://cloud.githubusercontent.com/assets/25598885/26369182/45d12d3c-3fca-11e7-98c8-9391b4608578.jpg)

**EDITAR ITEM DA PROGRAMAÇÃO: **
![gerenciarprogramacao-editar](https://cloud.githubusercontent.com/assets/25598885/26369183/45d33ab4-3fca-11e7-8449-72767acd66d5.jpg)
