### ISSUE TITLE
Como realizador do evento ou administrador eu quero ver a lista de Palestrantes do Evento

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#51]
Na área administrativa, o usuário com permissão de realizador do evento ou administrador deve poder ver a lista de Palestrantes do Evento. Essa tela permite, além de cadastrar palestrante, para cada item da lista:

- editar Palestrante
- excluir Palestrante
- filtro (pelo nome, e-mail, título da palestra)
- paginação

**Comment by RenatoMAlves** [comment]
![tela - lista de palestrantes](https://cloud.githubusercontent.com/assets/15240553/26356035/238f3e7c-3fa1-11e7-91e7-29fc714b0b01.png)

**Comment by jacksongomesbr** [comment]
Sugestão: apresentar também a data da palestra (se houver essa informação).
