### ISSUE TITLE
Como realizador do evento ou administrador eu quero cadastrar um Palestrante do Evento

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#52]
Na área administrativa, o usuário com permissão de realizador do evento ou administrador deve poder cadastrar um Palestrante do Evento. Os dados para esse cadastro estão na [página do Evento](https://github.com/fswceulp/sistema-eventos-front/wiki/Evento), na Wiki.

**Comment by RenatoMAlves** [comment]
![tela - cadastro e edicao de palestrante](https://cloud.githubusercontent.com/assets/15240553/26355964/dfeb18b2-3fa0-11e7-9458-f64fe6bccbed.png)
