### ISSUE TITLE
Como realizador do evento ou administrador eu quero editar um Palestrante do Evento

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#53]
Na área administrativa, o usuário com permissão de realizador do evento ou administrador deve poder editar um Palestrante do Evento.

**Comment by RenatoMAlves** [comment]
![tela - cadastro e edicao de palestrante](https://cloud.githubusercontent.com/assets/15240553/26355938/ce6462a6-3fa0-11e7-8c61-679e2e497b2e.png)
