### ISSUE TITLE
Como realizador do evento ou administrador eu quero excluir um Palestrante do Evento

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#54]
Na área administrativa, o usuário com permissão de realizador do evento ou administrador deve poder ver a excluir um Palestrante do Evento. O sistema deve solicitar uma confirmação do usuário antes de proceder com a exclusão.

**Comment by RenatoMAlves** [comment]
![tela - exclusao de palestrante](https://cloud.githubusercontent.com/assets/15240553/26355888/ae60420e-3fa0-11e7-8174-ca512d7e8b14.png)
