### ISSUE TITLE
Como realizador do evento ou administrador eu quero cadastrar um Inscrito do Evento

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#56]
Na área administrativa, o usuário com permissão de realizador do evento ou administrador deve poder cadastrar um Inscrito do Evento. Os dados para o cadastro são:

- Nome completo
- E-mail

Opcionalmente, o usuário deve poder selecionar um Usuário (Pessoa) já existente no sistema.

O sistema deve usar o e-mail como chave para não permitir que duas pessoas com o mesmo e-mail possam fazer duas ou mais inscrições no Evento.

**Comment by leonardomdc96** [comment]
![c inscricao](https://cloud.githubusercontent.com/assets/25598661/26333733/680d98a2-3f36-11e7-8250-8d4f586ae021.jpg)
