### ISSUE TITLE
Como realizador do evento ou administrador eu quero editar um Inscrito do Evento

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#58]
Na área administrativa, o usuário com permissão de realizador do evento ou administrador deve poder editar um Inscrito do Evento.

**Comment by leonardomdc96** [comment]
![u inscricao](https://cloud.githubusercontent.com/assets/25598661/26333717/4b8de7e0-3f36-11e7-9dfb-233a495c19e9.jpg)

**Comment by jacksongomesbr** [comment]
Não precisa trabalhar com a opção de atividades do evento (como minicurso) na inscrição.
