### ISSUE TITLE
Como realizador do evento ou administrador eu quero excluir um Inscrito do Evento

### ISSUE THREAD

**Issue by jacksongomesbr** [fswceulp/sistema-eventos-front#59]
Na área administrativa, o usuário com permissão de realizador do evento ou administrador deve poder excluir um Palestrante do Evento. O sistema deve solicitar ao usuário uma confirmação antes de proceder com a exclusão.

**Comment by leonardomdc96** [comment]
![d inscricao](https://cloud.githubusercontent.com/assets/25598661/26333709/3c669686-3f36-11e7-8761-c93572538aa3.jpg)
